--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LuthMC/AFKZone
build-by-default: true
branches:
- master
projects:
  AFKZone:
    path: ""
    icon: icon.png
    depend:
     - src: Ifera/ScoreHud/ScoreHud
       version: 8.0.0
       branch: "master"
...
