name: AFKZone
main: Luthfi\AFKZone\AFKZone
author: Luthfi
version: 3.0.0
api: 5.0.0
depend: ["ScoreHud"]
website: https://github.com/LuthMC/AFKZone
commands:
  afkzone:
    description: Configure the AFKZone
    usage: /afkzone <wand|create|delete|ui>
    aliases: [az]
    permission: afkzone.cmd
permissions:
  afkzone.cmd:
    description: Allow player to configure the AFKZone
    default: op
